onerror {resume}
quietly virtual signal -install /lagarto_v_pipeline_control_tb/vif_vid_latch_instance { /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/d_i[4:0]} latency
quietly virtual signal -install /lagarto_v_pipeline_control_tb/vif_vid_latch_instance { /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/d_i[36:5]} data
quietly virtual function -install /lagarto_v_pipeline_control_tb/vif_vid_latch_instance -env /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance { &{/lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[4], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[3], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[2], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[1], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[0] }} latency001
quietly virtual function -install /lagarto_v_pipeline_control_tb/vif_vid_latch_instance -env /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance { &{/lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[36], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[35], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[34], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[33], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[32], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[31], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[30], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[29], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[28], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[27], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[26], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[25], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[24], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[23], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[22], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[21], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[20], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[19], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[18], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[17], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[16], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[15], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[14], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[13], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[12], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[11], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[10], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[9], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[8], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[7], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[6], /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/q_o[5] }} data001
quietly virtual signal -install /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance { /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/d_i[4:0]} latency
quietly virtual signal -install /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance { /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/d_i[36:5]} data
quietly virtual function -install /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance -env /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance { &{/lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[4], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[3], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[2], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[1], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[0] }} latency001
quietly virtual function -install /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance -env /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance { &{/lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[36], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[35], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[34], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[33], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[32], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[31], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[30], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[29], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[28], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[27], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[26], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[25], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[24], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[23], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[22], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[21], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[20], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[19], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[18], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[17], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[16], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[15], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[14], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[13], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[12], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[11], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[10], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[9], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[8], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[7], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[6], /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/q_o[5] }} data001
quietly virtual signal -install /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance { /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/d_i[4:0]} latency
quietly virtual signal -install /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance { /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/d_i[36:5]} data
quietly virtual function -install /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance -env /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance { &{/lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[4], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[3], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[2], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[1], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[0] }} latency001
quietly virtual function -install /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance -env /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance { &{/lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[36], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[35], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[34], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[33], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[32], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[31], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[30], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[29], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[28], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[27], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[26], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[25], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[24], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[23], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[22], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[21], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[20], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[19], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[18], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[17], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[16], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[15], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[14], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[13], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[12], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[11], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[10], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[9], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[8], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[7], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[6], /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/q_o[5] }} data001
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix binary /lagarto_v_pipeline_control_tb/clock_b
add wave -noupdate -radix binary /lagarto_v_pipeline_control_tb/reset_nb
add wave -noupdate -divider {Latency Control}
add wave -noupdate -radix unsigned /lagarto_v_pipeline_control_tb/latency_control_unit_instance/incoming_latency_i
add wave -noupdate -radix unsigned /lagarto_v_pipeline_control_tb/latency_control_unit_instance/current_latency_r
add wave -noupdate -radix binary /lagarto_v_pipeline_control_tb/halt_pipeline_w
add wave -noupdate -divider {Vector Instruction Fetch}
add wave -noupdate -radix binary /lagarto_v_pipeline_control_tb/fake_memory_request_w
add wave -noupdate -radix unsigned /lagarto_v_pipeline_control_tb/latency_b
add wave -noupdate -radix hexadecimal /lagarto_v_pipeline_control_tb/data_b
add wave -noupdate -divider {VIF/VID Latch}
add wave -noupdate -group vif_vid_latch_d -radix unsigned -childformat {{{/lagarto_v_pipeline_control_tb/vif_vid_latch_instance/latency[4]} -radix unsigned} {{/lagarto_v_pipeline_control_tb/vif_vid_latch_instance/latency[3]} -radix unsigned} {{/lagarto_v_pipeline_control_tb/vif_vid_latch_instance/latency[2]} -radix unsigned} {{/lagarto_v_pipeline_control_tb/vif_vid_latch_instance/latency[1]} -radix unsigned} {{/lagarto_v_pipeline_control_tb/vif_vid_latch_instance/latency[0]} -radix unsigned}} -subitemconfig {{/lagarto_v_pipeline_control_tb/vif_vid_latch_instance/d_i[4]} {-radix unsigned} {/lagarto_v_pipeline_control_tb/vif_vid_latch_instance/d_i[3]} {-radix unsigned} {/lagarto_v_pipeline_control_tb/vif_vid_latch_instance/d_i[2]} {-radix unsigned} {/lagarto_v_pipeline_control_tb/vif_vid_latch_instance/d_i[1]} {-radix unsigned} {/lagarto_v_pipeline_control_tb/vif_vid_latch_instance/d_i[0]} {-radix unsigned}} /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/latency
add wave -noupdate -group vif_vid_latch_d -radix hexadecimal /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/data
add wave -noupdate -expand -group vif_vid_latch_q -label latency -radix unsigned /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/latency001
add wave -noupdate -expand -group vif_vid_latch_q -label data -radix hexadecimal /lagarto_v_pipeline_control_tb/vif_vid_latch_instance/data001
add wave -noupdate -divider {VID/VRR Latch}
add wave -noupdate -group vid_vrr_latch_d -radix unsigned /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/latency
add wave -noupdate -group vid_vrr_latch_d -radix hexadecimal /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/data
add wave -noupdate -expand -group vid_vrr_latch_q -label latency -radix unsigned /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/latency001
add wave -noupdate -expand -group vid_vrr_latch_q -label data -radix hexadecimal /lagarto_v_pipeline_control_tb/vid_vrr_latch_instance/data001
add wave -noupdate -divider {VRR/VEXE Latch}
add wave -noupdate -group vrr_vexe_latch_d -radix unsigned /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/latency
add wave -noupdate -group vrr_vexe_latch_d -radix hexadecimal /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/data
add wave -noupdate -expand -group vrr_vexe_latch_q -label latency -radix unsigned /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/latency001
add wave -noupdate -expand -group vrr_vexe_latch_q -label data -radix hexadecimal /lagarto_v_pipeline_control_tb/vrr_exe_latch_instance/data001
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {384 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 197
configure wave -valuecolwidth 126
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {470 ns}
